import Head from 'next/head' 
import Image from "next/image"



import profileImage from '../public/p2.png'
import graphicDesign from '../public/design.png'
import code from '../public/code.png' 
import webImage from '../public/web1.png' 


//framer

import { motion } from 'framer-motion'

// Icons
import { BsFillMoonStarsFill, BsWhatsapp } from "react-icons/bs";
import { FaGithub } from "react-icons/fa";
import { FaLinkedin } from "react-icons/fa";
import { IoLogoWhatsapp } from "react-icons/io";

//hooks 

import react,{ useState } from 'react'; 


export default function Home() {
  //function

  const [darkMode ,setdarkMode] = useState(false);
  return (
    <div className={darkMode ? " dark:" : " "}>
      <Head>
        <title>Dimuth Nilanjana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
          @import 
          url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;700&display=swap');
        </style>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-poppins text-black   bg-blue-100 min-h-screen 
      px-10 md:px-20 lg:40  dark:bg-black">
        {/* nav and hero */}
        <section>
          {/* nav */}
          <nav className="py-10 flex justify-between">
            <h1 className=' text-sm md:text-xl' > Dimuth Nilanjana</h1>
            <ul className="flex items-center">
              <li>
                {/* icon */}
                <BsFillMoonStarsFill  
                onclick={() => setdarkMode(! darkMode)}
                className=' cursor-pointer text-xs mx-5'/>

              </li>
              <li>
                <a href=""
                className=' bg-blue-600 text-white px-4 py-2 border-none rounded-md text-sm'
                >Resume</a>
              </li>


            </ul>
          </nav>

          {/* hero */}
          <div className=' text-center p-10'>
            <h1 className=' text-3xl font-bold text-blue-900
             md:text-5xl lg:text-7xl lg:mb-4'>Dimuth Nilanjana</h1>
            <h3 className=' text-lg py-4
            md:text-3xl'>Web Developer , UI/UX Designer and Brand identity Designer</h3>
            <p className=' text-sm py-4 leading-6 text-center max-w-xl mx-auto md:text-md'>
            jhgasdfhjgasjyfhgv
            ashjdfghjabfhjabfhjavfhjavfhjavfh
            jjhavfhgvafhgvaguyfugavfuyavfguhyavf
            huuyagfuyagfuygafuygasuyfgauyfhg

            </p>
          </div>
          {/* socials */}
          <div className=' text-4xl flex justify-center gap-10 text-gray-700'>
            <a href=""><FaGithub/></a>
            <a href=""><FaLinkedin/></a>
            <a href=""><IoLogoWhatsapp/></a>
          </div>
          {/* profile */}
          <motion.div 
          initial={{opacity:0 , scale:0.5}}
          animate={{ opacity:1 , scale:1}}
          transition={{duration:0.5}}
          whileHover={{scale:1.1 }}
          >

          <div className =" m-auto
           relative bg-gradient-to-b from-blue-200 w-80 p-5
            h-80 mt-20   rounded-full o " >
            <Image src ={ profileImage} alt="profile" layout='fill' objectFit='cover' />

          </div>

          </motion.div>


        </section>
        {/* servises */}
        <section>
          <div>
            <h2 className=' text-2xl py-5 font-bold opacity-75 text-gray-800'>Servises I Offer</h2>
            <p className=' text-sm py-5'>
            jhgasdfhjgasjyfhgv
            ashjdfghjabfhjabfhjavfhjavfhjavfh
            jjhavfhgvafhgvaguyfugavfuyavfguhyavf
            huuyagfuyagfuygafuygasuyfgauyfhg

            </p>
          </div>
          {/* servises cards */}


          <div className='md:flex lg:flex mx-auto gap-10'>
            {/* card 1 */}

            <motion.div
            whileHover={{scale:1.1 }}
            whileTap={{scale:0.9}}
            >

            <div className=' bg-blue-900 text-center shadow-sm p-5 rounded-xl my-5'>
              <Image src={graphicDesign} alt="design" width={100} height={100} 
              className=' inline'/>
              <h2 className=' text-white text-xl font-bold'>Graphic Designs</h2>
              <p className='text-white opacity-80 text-sm'>huuyagfuyagfuygafuygasuyfgauyfhg</p>
            </div>

            </motion.div>
            

            <div className=' bg-blue-900 text-center shadow-sm p-5 rounded-xl my-5'>
              <Image src={code} alt="design" width={100} height={100} 
              className=' inline'/>
              <h2 className=' text-white text-xl font-bold'>Web Development</h2>
              <p className='text-white opacity-80 text-sm'>huuyagfuyagfuygafuygasuyfgauyfhg</p>
            </div>
            
            <div className=' bg-blue-900 text-center shadow-sm p-5 rounded-xl my-5'>
              <Image src={graphicDesign} alt="design" width={100} height={100} 
              className=' inline'/>
              <h2 className=' text-white text-xl font-bold'>UI/UX Designs</h2>
              <p className='text-white opacity-80 text-sm'>huuyagfuyagfuygafuygasuyfgauyfhg</p>
            </div>
            
            
          </div>
        </section>
        {/* portfolio */}
        <section>
          <div >
            <h2 className=' text-2xl py-5 font-bold opacity-75 text-gray-800'>Portfolio</h2>
            <p className=' text-sm py-5'>
            jhgasdfhjgasjyfhgv
            ashjdfghjabfhjabfhjavfhjavfhjavfh
            jjhavfhgvafhgvaguyfugavfuyavfguhyavf
            huuyagfuyagfuygafuygasuyfgauyfhg

            </p>
            {/* Images */}
            <div className=' flex flex-col lg:flex-row lg:flex-wrap'>
              
              <div className="basis-1/3 flex-1">
            <Image src={webImage} alt='webImage' layout=' responsive'
            className=' rounded-lg object-cover py-5'/>
              </div>
              
              <div className="basis-1/3 flex-1">
            <Image src={webImage} alt='webImage' layout=' responsive'
            className=' rounded-lg object-cover py-5'/>
              </div>
             
              <div className="basis-1/3 flex-1">
            <Image src={webImage} alt='webImage' layout=' responsive'
            className=' rounded-lg object-cover py-5'/>
              </div>
              
              <div className="basis-1/3 flex-1">
            <Image src={webImage} alt='webImage' layout=' responsive'
            className=' rounded-lg object-cover py-5'/>
              </div>
              
              <div className="basis-1/3 flex-1">
            <Image src={webImage} alt='webImage' layout=' responsive'
            className=' rounded-lg object-cover py-5'/>
              </div>
              
              <div className="basis-1/3 flex-1">
            <Image src={webImage} alt='webImage' layout=' responsive'
            className=' rounded-lg object-cover py-5'/>
              </div>


            </div>
           
          </div>
        </section>
        {/* footer */}
        <footer className=' border-t-2 border-black opacity-80 text-sm
        flex  flex-col gap-5 items-center justify-center py-10 lh:flex-row lg:items-center'>
          <h3 className='text-lg font-bold'>Contact me for more Details</h3>
          <p className=' py-4 opacity-40'> Lorem ipsum, dolor sit amet consectetur adipisicing elit.
             Magnam dolor reiciendis at qui ullam soluta nesciunt! Iure explicabo 
             impedit omnis! Officia odit cum est quis numquam perspiciatis 
             doloremque alias modi?
          </p>
          <div className=' text-2xl flex justify-center gap-10 text-gray-700'>
            <a href=""><FaGithub/></a>
            <a href=""><FaLinkedin/></a>
            <a href=""><IoLogoWhatsapp/></a>
          </div>

          <div>
            <p className=' lg:text-sm justify-center inline-flex text-xs 
            opacity-30'>copyright (c) 2023 Inc. All rights reserved. Dimuth Nilanjana</p>
          </div>

        </footer>
    
      </main>
    </div>
  )
}
